print("Input")
nama = input("Nama : ")
nim = input("NIM : ")
paralel = input("Kelas Paralel : ")
ttl = input("Tempat/Tanggal Lahir : ")
alamat = input("Alamat : ")
hobby = input("Hobby : ")
telp = input("No Telepon : ")

print("\nOutput")
print("Nama : " + nama)
print("NIM : " + nim)
print("Kelas Paralel : " + paralel)
print("Tempat/Tanggal Lahir : " + ttl)
print("Alamat : " + alamat)
print("Hobby : " + hobby)
print("No Telepon : " + telp)